pipelines:
  custom:
    dev:
      - step:
          name: Building App
          image: node:14
          caches:
            - node
          script:
            - npm install
            - unset CI
            - npm run build
          artifacts:
            - build/**
      - step:
          name: deployment on S3
          deployment: Dev
          script:
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                # AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                # AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                # AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: "build"
                ACL: "public-read"